"
!!!GUI for pillar
I am a package of two different GUI's for the ''pillar'' markdown.


!!!! PillarTextPresenter
Is a simple Spec editor for pillar rendering


!!!! Calypso
I provide some extensions to the class browser Calypso. I allow rendering of package and class comments in pillar. 
"
Class {
	#name : #ManifestPillarTextPresenter,
	#superclass : #PackageManifest,
	#category : #'Pillar-TextPresenter-Manifest'
}
